// Generated by Selenium IDE

using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;

namespace SeleniumTests;

public class SuiteTests : IDisposable {
  public IWebDriver Driver {get; private set;} = new FirefoxDriver();
  private AccountData _accountData = new("maratabashevabashev@yandex.ru", "randomPassword123");

  public void Dispose()
  {
    Driver.Quit();
  }
  
  [Fact]
  public void TweekTest() {
    GoToUrl();
    Login(_accountData);
    CreateTask();
    CreateAndDeleteTask();
    EditTask();
    Logout();
  }

  private void GoToUrl()
  {
    Driver.Navigate().GoToUrl("https://tweek.so/ru");
  }

  private void EditTask()
  {
    FindElement(".\\_list_13lvv_22:nth-child(1) span").Click();
    FindElement(".RichNotes-button:nth-child(1)").Click();
    FindElement(".\\_input_dq3mo_15.\\_input_uyi05_1").Click();
    FindElement(".\\_input_dq3mo_15.\\_input_uyi05_1").Clear();
    FindElement(".\\_input_dq3mo_15.\\_input_uyi05_1").SendKeys("Edit task name");
    FindElement(".\\_input_dq3mo_15.\\_input_uyi05_1").SendKeys(Keys.Enter);
    Thread.Sleep(1000);
  }

  private IWebElement FindElement(string selector)
  {
    return Driver.FindElement(By.CssSelector(selector));
  }

  private void CreateAndDeleteTask()
  {
    FindElement(".\\_list_13lvv_22:nth-child(3) .\\_body_1wvuv_92").Click();
    FindElement(".\\_input_15t7a_19").SendKeys("task to delete");
    FindElement(".App").Click();
    FindElement("._list_13lvv_22:nth-child(1) ._cell_1wvuv_23:nth-child(2)").Click();
    FindElement("svg:nth-child(2)").Click();
    Thread.Sleep(1000);
  }

  private void CreateTask()
  {
    FindElement(".\\_input_15t7a_19").Click();
    FindElement(".\\_input_15t7a_19").SendKeys("Do task");
  }

  private void Logout()
  {
    FindElement(".\\_bars_1i8t4_107").Click();
    FindElement(".\\_backdrop_1ewsq_1").Click();
    FindElement(".\\_profile_1i8t4_82").Click();
    FindElement(".\\_footerLink_1c22j_104:nth-child(2)").Click();
  }

  private void Login(AccountData accountData)
  {
    FindElement(".\\_variantOutlined_w81oo_35").Click();
    Driver.FindElement(By.Name("email")).SendKeys(accountData.Mail);
    Driver.FindElement(By.Name("password")).SendKeys(accountData.Password);
    FindElement(".\\_fullWidth_w81oo_20").Click();
    Thread.Sleep(5000);
  }
}